import { Text } from "./Text";
import { Heading } from "./Heading";
import { Input } from "./Input";
import { Img } from "./Img";
import { Button } from "./Button";
import { ReactTable } from "./ReactTable";
import { SelectBox } from "./SelectBox";
import Divider from "./Divider";
import Modal from "./Modal";
export { Text, Heading, Input, Img, Button, ReactTable, SelectBox, Divider };
